clear:
	./vendor/bin/duster fix
	./vendor/bin/duster fix --dirty

run: 
	art octane:start --port=

build-run:
	$(eval TAG := $(shell date +%Y%m%d%H%M))
	echo "Generated by Makefile on $(shell date)" > /dev/null
	docker build --rm -t github/tour:$(TAG) -f Dockerfile.php .
	docker stop tour || true
	docker run --rm --net bridge -p 8000:8000 --name tour -d github/tour:$(TAG)
